### ISSUE TITLE
Using my own input video for summarization

### ISSUE THREAD

**Issue by chibexme** [yashkolli/Video-Summarization-Using-Attention#6]
I will like to know how to use my own input video for summarization. 

Is there any special processing that I will have to carry out on the input video first?

If yes, what are the procedures?

Thanks in anticipation.

**Comment by yashkolli** [comment]
You can use the generate summary script for your own video. Just make sure you only retain the generating summary part of the script, because that script does more job than just generating a summary. You should be good to go with that.

Although it will generate a summary for your own video, if your video doesn't fall in the types of videos that you used for training your model, the summary might not be a good one.

**Comment by chibexme** [comment]
@yashkolli I can't get to figure somethings out: 
1 - You mentioned [here](https://github.com/yashkolli/Video-Summarization-Using-Attention/issues/4#issuecomment-899063992), that I should use preprocessed dataset linked in the readme page. 
I've used it to train and I didn't get any error. But it seems like that dataset can't be used to summary any other video aside the ones you linked [here](https://github.com/yashkolli/Video-Summarization-Using-Attention/issues/5#issuecomment-903900775).
I tried to generate summary using my my input video of 5mins, but it hanged my laptop(HP Omen 16gb ram) until force restart.

2 - If I generate summary for the linked [video](https://github.com/yashkolli/Video-Summarization-Using-Attention/issues/5#issuecomment-903900775) it worked perfectly. I noticed that the linked videos have randomized names. Are there any preprocessing done on the videos first? 

3 - There are some files that are bundled with the video files (.tsv and .m files), what are there purpose in training and summarization?

4 - If I must generate my own dataset to train the model to summarize my own videos, are there any sample scripts I can reference to guide me?
